name: lockie_account
description: A generated module for LockieApp App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.3
  
  firebase_core: ^1.10.5
  cloud_firestore: ^3.1.4
  firebase_auth: ^3.3.11
  cloud_functions: ^3.2.10
  firebase_dynamic_links: ^4.0.6

  shared_preferences: ^2.0.13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: