name: lockie_locker
description: A generated module for Lockie App.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  equatable: ^2.0.3
  firebase_core: ^1.10.5
  cloud_firestore: ^3.1.4

dev_dependencies:
  flutter_lints:
  flutter_test:
    sdk: flutter