name: lockie_theme
description: Theme module for the Lockie App.
publish_to: none
version: 0.1.2

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.6.10
  url_launcher: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: null
  